algorithm:
  algorithm_name: "RSA_generate_key_ex"
  # path to documentation of target algorithm
  documentation: documentation/crypto/libgcrypt/RSA_generate_key_ex.txt
  algorithm_code: documentation/crypto/libgcrypt/RSA_generate_key_ex-code.txt
  # path to example code
  example_code: documentation/cryptofuzz_code2/
  # required argument
  arguments: "public_exponent,bits"
  # create list (ordered)
  file_to_create: "gen_repository.py,tests.h,tests.cpp,mutatorpool.h,mutatorpool.cpp,components.h,components.cpp,util.cpp,util.h,operations.h,operation.cpp,libgcrypt_module.h,libgcrypt_module.cpp,module.h,executor.h,executor.cpp,driver.cpp,mutator.cpp"
  # path to store the results
  output: prompt3/0
  cryptofuzz_dir: /workdir/cryptofuzz_libgcrypt-1.10.2-harness2/
"files":
- "name": "mutatorpool.cpp"
  "dependency": "mutatorpool.h"
- "name": "components.h"
  "dependency": "mutatorpool.h"
- "name": "components.cpp"
  "dependency": "mutatorpool.h"
- "name": "util.cpp"
  "dependency": "mutatorpool.h"
- "name": "util.h"
  "dependency": "mutatorpool.h"
- "name": "executor.h"
  "dependency": "components.h"
- "name": "executor.cpp"
  "dependency": "executor.h"
- "name": "libgcrypt_module.cpp"
  "dependency": "components.h,operations.h"
- "name": "module.h"
  "dependency": "libgcrypt_module.cpp"
- "name": "driver.cpp"
  "dependency": "module.h"
- "name": "mutator.cpp"
  "dependency": "components.h,operations.h"
- "name": "tests.cpp"
  "dependency": "tests.h"