MutatorPool<CurvePrivkey_Pair, cryptofuzz::config::kMutatorPoolSize> Pool_CurvePrivkey;
MutatorPool<CurveKeypair_Pair, cryptofuzz::config::kMutatorPoolSize> Pool_CurveKeypair;
MutatorPool<CurveECDSASignature_Pair, cryptofuzz::config::kMutatorPoolSize> Pool_CurveECDSASignature;
MutatorPool<CurveECC_Point_Pair, cryptofuzz::config::kMutatorPoolSize> Pool_CurveECC_Point;
MutatorPool<CurveBLSSignature_Pair, cryptofuzz::config::kMutatorPoolSize> Pool_CurveBLSSignature;
MutatorPool<CurveBLSG1_Pair, cryptofuzz::config::kMutatorPoolSize> Pool_CurveBLSG1;
MutatorPool<CurveBLSG2_Pair, cryptofuzz::config::kMutatorPoolSize> Pool_CurveBLSG2;
MutatorPool<std::string, cryptofuzz::config::kMutatorPoolSize> Pool_Bignum;
MutatorPool<std::string, cryptofuzz::config::kMutatorPoolSize> Pool_Bignum_Primes;
MutatorPool<Fp12, cryptofuzz::config::kMutatorPoolSize> Pool_Fp12;
MutatorPool<BLS_BatchSignature_, cryptofuzz::config::kMutatorPoolSize> Pool_BLS_BatchSignature;
MutatorPool<std::string, cryptofuzz::config::kMutatorPoolSize> Pool_DH_PrivateKey;
MutatorPool<std::string, cryptofuzz::config::kMutatorPoolSize> Pool_DH_PublicKey;
MutatorPool<RSAPrivateKey_Pair, cryptofuzz::config::kMutatorPoolSize> Pool_RSA_PrivateKey;
MutatorPool<RSA_PublicKey_Pair, cryptofuzz::config::kMutatorPoolSize> Pool_RSA_PublicKey;
MutatorPool<RSAKeypair_Pair, cryptofuzz::config::kMutatorPoolSize> Pool_RSAKeypair;

template class MutatorPool<CurvePrivkey_Pair, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<CurveKeypair_Pair, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<CurveECDSASignature_Pair, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<CurveECC_Point_Pair, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<CurveBLSSignature_Pair, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<CurveBLSG1_Pair, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<CurveBLSG2_Pair, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<Fp12, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<BLS_BatchSignature_, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<std::string, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<RSAKeypair_Pair, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<RSAPrivateKey_Pair, cryptofuzz::config::kMutatorPoolSize>;
template class MutatorPool<RSA_PublicKey_Pair, cryptofuzz::config::kMutatorPoolSize>;