algorithm:
  algorithm_name: "X509_STORE_CTX_verify"
  # path to documentation of target algorithm
  documentation: documentation/crypto/X509_STORE_CTX_verify.txt
  algorithm_code: documentation/crypto/X509_STORE_CTX_verify-code2.txt
  # path to example code
  example_code: documentation/cryptofuzz_code2
  # required argument
  arguments: "ntlsa,ncert,noncheck,ntlsa_data"
  # create list (ordered)
  file_to_create: "tests.h,tests.cpp,mutatorpool.h,mutatorpool.cpp,components.h,components.cpp,util.cpp,util.h,operations.h,operation.cpp,openssl_module.h,module.cpp,module.h,executor.h,executor.cpp,driver.cpp,mutator.cpp"
  # path to store the results
  output: prompt0/0
  cryptofuzz_dir: /workdir/cryptofuzz_openssl-3.3.0-dev-harness3/
"files":
- "name": "mutatorpool.cpp"
  "dependency": "mutatorpool.h"
- "name": "components.h"
  "dependency": "mutatorpool.h"
- "name": "components.cpp"
  "dependency": "mutatorpool.h"
- "name": "util.cpp"
  "dependency": "mutatorpool.h"
- "name": "util.h"
  "dependency": "mutatorpool.h"
- "name": "executor.h"
  "dependency": "components.h"
- "name": "executor.cpp"
  "dependency": "executor.h"
- "name": "module.cpp"
  "dependency": "components.h,operations.h"
- "name": "module.h"
  "dependency": "module.cpp"
- "name": "driver.cpp"
  "dependency": "module.h"
- "name": "mutator.cpp"
  "dependency": "components.h,operations.h"
- "name": "tests.cpp"
  "dependency": "tests.h"